import http from "node:http";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { load, save, id } from "./store.js";
import { assertPence, isAvailable, createQuote, confirmBooking } from "./core.js";
import { listSuppliers, searchFarnell } from "./suppliers.js";
import { searchInternalCatalog, listInternalCatalog } from "./catalog.js";
import { listMarketCatalog, searchMarketCatalog, listCompetitors } from "./market.js";
import { evaluateCatalogRow, CATALOG_STATES, IMAGE_PERMISSION_STATES } from "./catalog_contract.js";
import { buildAgentControl, runAgentCommand } from "./agents.js";
import { enrichAgentCommand } from "./intelligence.js";
